# Tiering\Invoke-MATITieringPhase2.ps1
# Phase 2 — Create Recommended Tiered Admin Accounts
# Creates dedicated admin accounts per tier from a CSV template,
# applies T0 hardening (Protected Users + AccountNotDelegated), and generates an HTML report.

function Invoke-MATITieringPhase2 {
    <#
    .SYNOPSIS
        Phase 2 — Interactive creation of recommended tiered admin accounts.
    .DESCRIPTION
        Guided, step-by-step deployment:
        1. Generate and fill the CSV template with the recommended tiered admin accounts to create
        2. Review and edit the mapping table (add, remove, change tier, skip entries)
        3. Confirm the account list before creation
        4. Create accounts in the correct tiered OUs with secure passwords
        5. Harden Tier 0 accounts (Protected Users + AccountNotDelegated)
        6. Generate an HTML deployment report
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RootPath,

        [Parameter(Mandatory)]
        [hashtable]$TieringConfig,

        [Parameter(Mandatory)]
        [string]$OutputDir
    )

    $ErrorActionPreference = 'Continue'
    $sw = [System.Diagnostics.Stopwatch]::StartNew()

    # Ensure output directory exists
    if (-not (Test-Path $OutputDir)) {
        New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
    }

    # Shorthand references
    $naming  = $TieringConfig.Naming
    $ouCfg   = $TieringConfig.OUStructure
    $domain  = Get-ADDomain
    $domainDN = $domain.DistinguishedName
    $dnsRoot  = $domain.DNSRoot

    # Determine base DN (container OU or domain root — matches Phase 1 deployment)
    $containerOU = $ouCfg.ContainerOU
    if ($containerOU) {
        $candidateDN = "OU=$containerOU,$domainDN"
        if ([adsi]::Exists("LDAP://$candidateDN")) {
            $baseDN = $candidateDN
        } else {
            $baseDN = $domainDN
        }
    } else {
        $baseDN = $domainDN
    }

    # Pre-check: verify Phase 1 OU structure exists
    $missingOUs = @()
    foreach ($tierKey in @('Tier0', 'Tier1', 'Tier2')) {
        $tierName = $ouCfg.$tierKey
        $accountsOU = "OU=Accounts,OU=$tierName,$baseDN"
        if (-not ([adsi]::Exists("LDAP://$accountsOU"))) {
            $missingOUs += $accountsOU
        }
    }
    if ($missingOUs.Count -gt 0) {
        Write-Host "`n  [ERROR] Phase 1 OU structure not found. Run Phase 1 first." -ForegroundColor Red
        foreach ($m in $missingOUs) {
            Write-Host "    Missing: $m" -ForegroundColor DarkGray
        }
        Write-Host ""
        return
    }

    # Results tracker
    $results = @{
        Source                = ''
        BaseDN                = $baseDN
        ContainerOU           = $containerOU
        CsvTemplatePath       = ''
        InputCsvPath          = ''
        NamingPattern         = ''
        DisplayNamePattern    = ''
        DescriptionPattern    = ''
        AccountsMapped        = [System.Collections.Generic.List[object]]::new()
        AccountsCreated       = [System.Collections.Generic.List[object]]::new()
        AccountsExisted       = [System.Collections.Generic.List[object]]::new()
        AccountsSkipped       = [System.Collections.Generic.List[object]]::new()
        HardeningApplied      = [System.Collections.Generic.List[object]]::new()
        GroupMembershipsAdded = [System.Collections.Generic.List[string]]::new()
        Errors                = [System.Collections.Generic.List[string]]::new()
    }

    # ================================================================
    # Banner
    # ================================================================
    Write-Host "`n  ══════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "   Phase 2 — Create Recommended Tiered Admin Accounts" -ForegroundColor Cyan
    Write-Host "  ══════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "   Creates recommended admin accounts per tier from a CSV plan." -ForegroundColor DarkGray
    Write-Host "   SamAccountName, DisplayName, and Description will be generated by the wizard.`n" -ForegroundColor DarkGray

    # ================================================================
    # Helper: normalize name parts for generated account names
    # ================================================================
    function ConvertTo-NameToken {
        param([string]$Value)

        if ([string]::IsNullOrWhiteSpace($Value)) { return '' }
        return (($Value.Trim().ToLowerInvariant()) -replace "['`\s]+", '') -replace '[^a-z0-9.-]', ''
    }

    # ================================================================
    # Helper: build SamAccountName from selected pattern
    # ================================================================
    function Build-TieredSam {
        param(
            [string]$Tier,
            [string]$FirstName,
            [string]$LastName,
            [string]$Pattern
        )

        $tierNum = $Tier -replace 'T',''
        $tierCode = "T$tierNum"
        $tierPrefix = $tierCode.ToLowerInvariant()
        $firstToken = ConvertTo-NameToken -Value $FirstName
        $lastToken = ConvertTo-NameToken -Value $LastName
            $firstInitial = if ($firstToken.Length -gt 0) { $firstToken.Substring(0,1) } else { '' }

        $sam = switch ($Pattern) {
            'TIER_DOT_FIRST_DOT_LAST' {
                if ($lastToken) { "$tierPrefix.$firstToken.$lastToken" } else { "$tierPrefix.$firstToken" }
            }
            'TIER_DOT_LAST' {
                if ($lastToken) { "$tierPrefix.$lastToken" } else { "$tierPrefix.$firstToken" }
            }
            'TIER_DASH_FIRST_DOT_LAST' {
                if ($lastToken) { "$tierPrefix-$firstToken.$lastToken" } else { "$tierPrefix-$firstToken" }
            }
            'TIER_DASH_LAST' {
                if ($lastToken) { "$tierPrefix-$lastToken" } else { "$tierPrefix-$firstToken" }
            }
            'FIRST_DOT_LAST_DOT_TIER' {
                if ($lastToken) { "$firstToken.$lastToken.$tierPrefix" } else { "$firstToken.$tierPrefix" }
            }
            'TIER_DOT_FIRST' {
                if ($firstToken) { "$tierPrefix.$firstToken" } else { "$tierPrefix.$lastToken" }
            }
            'TIER_DOT_FIRSTINITIAL_DOT_LAST' {
                if ($lastToken) { "$tierPrefix.$firstInitial.$lastToken" } else { "$tierPrefix.$firstToken" }
            }
            'FIRSTINITIAL_DOT_LAST_DOT_TIER' {
                if ($lastToken) { "$firstInitial.$lastToken.$tierPrefix" } else { "$firstInitial.$tierPrefix" }
            }
            default {
                if ($lastToken) { "$tierPrefix.$firstToken.$lastToken" } else { "$tierPrefix.$firstToken" }
            }
        }

        $sam = $sam.ToLowerInvariant().Trim('.','-')

        if ($sam.Length -gt 20) {
            $sam = $sam.Substring(0,20).TrimEnd('.','-')
        }

        return $sam
    }

    # ================================================================
    # Helper: build DisplayName from selected pattern
    # ================================================================
    function Build-TieredDisplayName {
        param(
            [string]$Tier,
            [string]$FirstName,
            [string]$LastName,
            [string]$Pattern
        )

        $fullName = (@($FirstName, $LastName) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }) -join ' '
        $fullName = $fullName.Trim()

        switch ($Pattern) {
            'TIER_DASH_FULLNAME' { return "$Tier - $fullName".Trim() }
            'FULLNAME_PARENS_TIER' { return "$fullName ($Tier)".Trim() }
            'TIER_ADMIN_DASH_FULLNAME' { return "$Tier Admin - $fullName".Trim() }
            'FULLNAME_DASH_TIER_ADMIN' { return "$fullName - $Tier Admin".Trim() }
            'TIER_ADMIN_PARENS_FULLNAME' { return "$Tier Admin ($fullName)".Trim() }
            'FULLNAME_PARENS_TIER_ADMIN' { return "$fullName ($Tier Admin)".Trim() }
            default { return "$Tier - $fullName".Trim() }
        }
    }

    # ================================================================
    # Helper: build Description from selected pattern
    # ================================================================
    function Build-TieredDescription {
        param(
            [string]$Tier,
            [string]$FirstName,
            [string]$LastName,
            [string]$Pattern
        )

        $fullName = (@($FirstName, $LastName) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }) -join ' '
        $fullName = $fullName.Trim()

        switch ($Pattern) {
            'TIER_ADMIN_ACCOUNT_FOR_FULLNAME' { return "$Tier administrative account for $fullName".Trim() }
            'TIER_ACCOUNT_FOR_FULLNAME' { return "$Tier account for $fullName".Trim() }
            'TIER_ADMIN_DASH_FULLNAME' { return "$Tier admin - $fullName".Trim() }
            'PRIVILEGED_TIER_ACCOUNT_FOR_FULLNAME' { return "Privileged $Tier account for $fullName".Trim() }
            'FULLNAME_DASH_TIER_ADMIN_ACCOUNT' { return "$fullName - $Tier admin account".Trim() }
            default { return "$Tier administrative account for $fullName".Trim() }
        }
    }

    # ================================================================
    # Helper: generate cryptographically secure random password
    # ================================================================
    function New-RandomPassword {
        param([int]$Length = 24)
        $chars = 'abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!@#$%&*-_=+'
        $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
        $bytes = [byte[]]::new($Length)
        $rng.GetBytes($bytes)
        $password = -join ($bytes | ForEach-Object { $chars[$_ % $chars.Length] })
        $rng.Dispose()
        return $password
    }

    # ================================================================
    # Helper: generate the Phase 2 CSV template
    # ================================================================
    function New-Phase2CsvTemplate {
        param([string]$TemplatePath)

        $templateRows = @(
            [PSCustomObject]@{
                FirstName    = ''
                LastName     = ''
                AssignedTier = ''
            }
        )

        $templateRows | Export-Csv -Path $TemplatePath -NoTypeInformation -Encoding UTF8
    }

    # ================================================================
    # Helper: display the mapping table
    # ================================================================
    function Show-MappingTable {
        param([System.Collections.Generic.List[object]]$Accounts)
        Write-Host ""
        Write-Host "    ┌─────┬────────────────────────────┬──────────────────────────────┬──────┐" -ForegroundColor DarkGray
        Write-Host "    │  #  │ SamAccountName             │ DisplayName                  │ Tier │" -ForegroundColor DarkGray
        Write-Host "    ├─────┼────────────────────────────┼──────────────────────────────┼──────┤" -ForegroundColor DarkGray

        $i = 0
        foreach ($a in $Accounts) {
            $i++
            $a.Index = $i
            $newSam  = if ($a.NewSamAccountName.Length -gt 26) { $a.NewSamAccountName.Substring(0,25) + '~' } else { $a.NewSamAccountName }
            $display = if ($a.DisplayName.Length -gt 28) { $a.DisplayName.Substring(0,27) + '~' } else { $a.DisplayName }
            Write-Host ("    │ {0,-3} │ {1,-26} │ {2,-28} │ {3,-4} │" -f $i, $newSam, $display, $a.Tier)
        }
        Write-Host "    └─────┴────────────────────────────┴──────────────────────────────┴──────┘" -ForegroundColor DarkGray

        Write-Host "    Total: $($Accounts.Count)" -ForegroundColor DarkGray
    }

    # ================================================================
    # Step 1 — CSV Input
    # ================================================================
    Write-Host "  ─── Step 1/5: CSV Input ───────────────────────────────" -ForegroundColor Yellow

    $templateDir = Join-Path $RootPath 'Outputs\Tiering\Templates'
    if (-not (Test-Path $templateDir)) {
        New-Item -ItemType Directory -Force -Path $templateDir | Out-Null
    }
    $templatePath = Join-Path $templateDir 'MATI-Phase2-TieredAdminAccounts-Template.csv'
    New-Phase2CsvTemplate -TemplatePath $templatePath
    $results.CsvTemplatePath = $templatePath
    $results.Source = 'CSV'

    Write-Host "" 
    Write-Host "    Fill the CSV template with the admin accounts to create." -ForegroundColor White
    Write-Host "    Template path:" -ForegroundColor White
    Write-Host "      $templatePath" -ForegroundColor Cyan
    Write-Host "" 
    Write-Host "    CSV columns:" -ForegroundColor DarkGray
    Write-Host "      FirstName, LastName, AssignedTier" -ForegroundColor DarkGray
    Write-Host "" 

    $csvPath = Read-Host "    Enter completed CSV file path (or X to cancel)"
    if ($csvPath -match '^[Xx]$') {
        Write-Host "    Cancelled.`n" -ForegroundColor Yellow
        return
    }

    $accounts = [System.Collections.Generic.List[object]]::new()

    if (-not (Test-Path $csvPath)) {
        Write-Host "    [!] File not found: $csvPath" -ForegroundColor Red
        Write-Host "    [!] Fill the template CSV and run Phase 2 again.`n" -ForegroundColor Red
        return
    }

    $results.InputCsvPath = (Resolve-Path $csvPath).Path
    $csvData = Import-Csv $results.InputCsvPath
    $requiredColumns = @('FirstName', 'LastName', 'AssignedTier')
    $csvHeaders = if ($csvData.Count -gt 0) {
        @($csvData[0].PSObject.Properties.Name)
    } else {
        @()
    }
    $missingColumns = @($requiredColumns | Where-Object { $_ -notin $csvHeaders })
    if ($missingColumns.Count -gt 0) {
        Write-Host "    [!] Invalid CSV format. Missing required column(s): $($missingColumns -join ', ')" -ForegroundColor Red
        Write-Host "    [!] Expected columns: $($requiredColumns -join ', ')" -ForegroundColor Red
        return
    }

    Write-Host ""
    Write-Host "  ─── Step 1b/5: Naming & Presentation Format ───────────" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "    SamAccountName patterns:" -ForegroundColor White
    Write-Host "      [1] t0.firstname.lastname" -ForegroundColor Cyan
    Write-Host "      [2] t0.lastname" -ForegroundColor Cyan
    Write-Host "      [3] t0-firstname.lastname" -ForegroundColor Cyan
    Write-Host "      [4] t0-lastname" -ForegroundColor Cyan
    Write-Host "      [5] firstname.lastname.t0" -ForegroundColor Cyan
    Write-Host "      [6] t0.firstname" -ForegroundColor Cyan
    Write-Host "      [7] t0.f.lastname" -ForegroundColor Cyan
    Write-Host "      [8] f.lastname.t0" -ForegroundColor Cyan
    $samPatternChoice = Read-Host "    Select SamAccountName pattern [1-8]"
    $samPattern = switch ($samPatternChoice) {
        '2' { 'TIER_DOT_LAST' }
        '3' { 'TIER_DASH_FIRST_DOT_LAST' }
        '4' { 'TIER_DASH_LAST' }
        '5' { 'FIRST_DOT_LAST_DOT_TIER' }
        '6' { 'TIER_DOT_FIRST' }
        '7' { 'TIER_DOT_FIRSTINITIAL_DOT_LAST' }
        '8' { 'FIRSTINITIAL_DOT_LAST_DOT_TIER' }
        default { 'TIER_DOT_FIRST_DOT_LAST' }
    }

    Write-Host ""
    Write-Host "    DisplayName patterns:" -ForegroundColor White
    Write-Host "      [1] T0 - FirstName LastName" -ForegroundColor Cyan
    Write-Host "      [2] FirstName LastName (T0)" -ForegroundColor Cyan
    Write-Host "      [3] T0 Admin - FirstName LastName" -ForegroundColor Cyan
    Write-Host "      [4] FirstName LastName - T0 Admin" -ForegroundColor Cyan
    Write-Host "      [5] T0 Admin (FirstName LastName)" -ForegroundColor Cyan
    Write-Host "      [6] FirstName LastName (T0 Admin)" -ForegroundColor Cyan
    $displayPatternChoice = Read-Host "    Select DisplayName pattern [1-6]"
    $displayPattern = switch ($displayPatternChoice) {
        '2' { 'FULLNAME_PARENS_TIER' }
        '3' { 'TIER_ADMIN_DASH_FULLNAME' }
        '4' { 'FULLNAME_DASH_TIER_ADMIN' }
        '5' { 'TIER_ADMIN_PARENS_FULLNAME' }
        '6' { 'FULLNAME_PARENS_TIER_ADMIN' }
        default { 'TIER_DASH_FULLNAME' }
    }

    Write-Host ""
    Write-Host "    Description patterns:" -ForegroundColor White
    Write-Host "      [1] T0 administrative account for FirstName LastName" -ForegroundColor Cyan
    Write-Host "      [2] T0 account for FirstName LastName" -ForegroundColor Cyan
    Write-Host "      [3] T0 admin - FirstName LastName" -ForegroundColor Cyan
    Write-Host "      [4] Privileged T0 account for FirstName LastName" -ForegroundColor Cyan
    Write-Host "      [5] FirstName LastName - T0 admin account" -ForegroundColor Cyan
    $descriptionPatternChoice = Read-Host "    Select Description pattern [1-5]"
    $descriptionPattern = switch ($descriptionPatternChoice) {
        '2' { 'TIER_ACCOUNT_FOR_FULLNAME' }
        '3' { 'TIER_ADMIN_DASH_FULLNAME' }
        '4' { 'PRIVILEGED_TIER_ACCOUNT_FOR_FULLNAME' }
        '5' { 'FULLNAME_DASH_TIER_ADMIN_ACCOUNT' }
        default { 'TIER_ADMIN_ACCOUNT_FOR_FULLNAME' }
    }

    $results.NamingPattern = $samPattern
    $results.DisplayNamePattern = $displayPattern
    $results.DescriptionPattern = $descriptionPattern

    $csvCount = 0
    foreach ($row in $csvData) {
        $tierValue = $row.AssignedTier
        $tier = [string]$tierValue
        if (-not $tier) { continue }
        $tier = $tier.ToUpper().Trim()
        if ($tier -notin @('T0','T1','T2')) {
            Write-Host "    [!] Skipping invalid tier '$tierValue' for $($row.FirstName) $($row.LastName)" -ForegroundColor Yellow
            continue
        }

        $fn = ([string]$row.FirstName).Trim()
        $ln = ([string]$row.LastName).Trim()
        if (-not $fn) {
            Write-Host "    [!] Skipping row with empty FirstName." -ForegroundColor Yellow
            continue
        }

        $newSam = Build-TieredSam -Tier $tier -FirstName $fn -LastName $ln -Pattern $samPattern
        $displayName = Build-TieredDisplayName -Tier $tier -FirstName $fn -LastName $ln -Pattern $displayPattern
        $accountDescription = Build-TieredDescription -Tier $tier -FirstName $fn -LastName $ln -Pattern $descriptionPattern

        $isDupe = $accounts | Where-Object { $_.NewSamAccountName -eq $newSam }
        if ($isDupe) {
            Write-Host "    [!] Duplicate target account in CSV: $newSam — skipping duplicate row" -ForegroundColor Yellow
            continue
        }

        $accounts.Add([PSCustomObject]@{
            Index             = $accounts.Count + 1
            Source            = 'CSV'
            FirstName         = $fn
            LastName          = $ln
            Tier              = $tier
            DisplayName       = $displayName
            Description       = $accountDescription
            NewSamAccountName = $newSam
            Action            = 'Create'
        })
        $csvCount++
    }

    Write-Host "    CSV imported: $csvCount account(s)" -ForegroundColor Green

    if ($accounts.Count -eq 0) {
        Write-Host "`n    [!] No accounts to process.`n" -ForegroundColor Yellow
        return
    }

    # ================================================================
    # Step 2 — Review Generated Accounts
    # ================================================================
    Write-Host "`n  ─── Step 2/5: Review Generated Accounts ───────────────" -ForegroundColor Yellow
    Show-MappingTable -Accounts $accounts
    Write-Host ""
    Write-Host "    Review the generated accounts above." -ForegroundColor White
    Write-Host "    Type Y to continue or N to cancel." -ForegroundColor Cyan
    Write-Host ""

    $confirm = Read-Host "    Continue? (Y/N)"
    if ($confirm -notmatch '^[Yy]') {
        Write-Host "    Cancelled.`n" -ForegroundColor Yellow
        return
    }

    # Store all mapped accounts (including skipped)
    foreach ($a in $accounts) { $results.AccountsMapped.Add($a) }

    # Filter to actionable accounts
    $toCreate = @($accounts)
    $toSkip   = @()
    foreach ($s in $toSkip) {
        $results.AccountsSkipped.Add([PSCustomObject]@{
            SamAccountName = $s.NewSamAccountName
            DisplayName    = $s.DisplayName
            Tier           = $s.Tier
            Description    = $s.Description
            Reason         = 'Skipped by user'
        })
    }

    if ($toCreate.Count -eq 0) {
        Write-Host "`n    [!] No accounts selected for creation.`n" -ForegroundColor Yellow
        return
    }

    # ================================================================
    # Step 3 — Create Accounts
    # ================================================================
    Write-Host "`n  ─── Step 3/5: Creating Accounts ────────────────────────" -ForegroundColor Yellow

    # Password export list (temporarily held in memory, exported to CSV after)
    $passwordExport = [System.Collections.Generic.List[object]]::new()

    foreach ($acct in $toCreate) {
        $tierNum    = $acct.Tier -replace 'T',''
        $tierOUName = $ouCfg."Tier$tierNum"
        $targetOU   = "OU=Accounts,OU=$tierOUName,$baseDN"
        $groupName  = "$($naming.GroupPrefix)$tierNum-Admins"

        $sam         = $acct.NewSamAccountName
        $upn         = "$sam@$dnsRoot"
        $displayName = $acct.DisplayName
        $description = $acct.Description

        # Check if account already exists
        try {
            $existing = Get-ADUser -Filter "SamAccountName -eq '$sam'" -ErrorAction SilentlyContinue
            if ($existing) {
                Write-Host "    [=] $sam — already exists (skipped creation)" -ForegroundColor DarkGray
                $results.AccountsExisted.Add([PSCustomObject]@{
                    SamAccountName = $sam
                    Tier           = $acct.Tier
                    FirstName      = $acct.FirstName
                    LastName       = $acct.LastName
                    DisplayName    = $displayName
                    Description    = $description
                    TargetOU       = $targetOU
                    TargetGroup    = $groupName
                    Source         = $acct.Source
                })
                # Still try to add to group
                try {
                    Add-ADGroupMember -Identity $groupName -Members $sam -ErrorAction Stop
                    Write-Host "    [+] $sam → $groupName" -ForegroundColor Green
                    $results.GroupMembershipsAdded.Add("$sam -> $groupName")
                } catch {
                    if ($_.Exception.Message -notmatch 'already a member') {
                        $results.Errors.Add("Failed to add $sam to ${groupName}: $($_.Exception.Message)")
                    }
                }
                continue
            }
        } catch { }

        # Generate secure random password
        $pwPlain = New-RandomPassword -Length 24
        $pw = ConvertTo-SecureString $pwPlain -AsPlainText -Force

        try {
            $userParams = @{
                Name                  = $sam
                SamAccountName        = $sam
                UserPrincipalName     = $upn
                GivenName             = $acct.FirstName
                Surname               = $acct.LastName
                DisplayName           = $displayName
                Description           = $description
                Path                  = $targetOU
                AccountPassword       = $pw
                Enabled               = $true
                ChangePasswordAtLogon = $true
                PasswordNeverExpires  = $false
            }
            New-ADUser @userParams
            Write-Host "    [+] Created: $sam → $targetOU" -ForegroundColor Green

            $results.AccountsCreated.Add([PSCustomObject]@{
                SamAccountName = $sam
                Tier           = $acct.Tier
                FirstName      = $acct.FirstName
                LastName       = $acct.LastName
                DisplayName    = $displayName
                Description    = $description
                TargetOU       = $targetOU
                TargetGroup    = $groupName
                Source         = $acct.Source
            })

            $passwordExport.Add([PSCustomObject]@{
                SamAccountName    = $sam
                Tier              = $acct.Tier
                TemporaryPassword = $pwPlain
                MustChangeAtLogon = 'Yes'
            })

            # Add to tier admins group
            try {
                Add-ADGroupMember -Identity $groupName -Members $sam
                Write-Host "    [+] $sam → $groupName" -ForegroundColor Green
                $results.GroupMembershipsAdded.Add("$sam -> $groupName")
            } catch {
                $errMsg = "Failed to add $sam to ${groupName}: $($_.Exception.Message)"
                Write-Host "    [!] $errMsg" -ForegroundColor Red
                $results.Errors.Add($errMsg)
            }
        } catch {
            $errMsg = "Failed to create ${sam}: $($_.Exception.Message)"
            Write-Host "    [!] $errMsg" -ForegroundColor Red
            $results.Errors.Add($errMsg)
            $results.AccountsSkipped.Add([PSCustomObject]@{
                SamAccountName = $sam
                Tier           = $acct.Tier
                Reason         = $_.Exception.Message
            })
        }
    }

    # Export temporary passwords to CSV
    if ($passwordExport.Count -gt 0) {
        $pwCsvPath = Join-Path $OutputDir "MATI-Phase2-Passwords-$(Get-Date -Format 'yyyyMMdd-HHmmss').csv"
        $passwordExport | Export-Csv -Path $pwCsvPath -NoTypeInformation -Encoding UTF8
        Write-Host ""
        Write-Host "    ┌─────────────────────────────────────────────────────────┐" -ForegroundColor Yellow
        Write-Host "    │  TEMPORARY PASSWORDS EXPORTED                           │" -ForegroundColor Yellow
        Write-Host "    │  $pwCsvPath" -ForegroundColor Yellow
        Write-Host "    │                                                         │" -ForegroundColor Yellow
        Write-Host "    │  ⚠ Distribute securely and DELETE this file after use.  │" -ForegroundColor Red
        Write-Host "    │  All accounts must change password at first logon.      │" -ForegroundColor Yellow
        Write-Host "    └─────────────────────────────────────────────────────────┘" -ForegroundColor Yellow
    }

    # ================================================================
    # Step 5 — Harden Tier 0 Accounts
    # ================================================================
    Write-Host "`n  ─── Step 4/5: Hardening Tier 0 Accounts ────────────────" -ForegroundColor Yellow

    # Gather all T0 accounts (newly created + already existed)
    $t0Accounts = @()
    $t0Accounts += @($results.AccountsCreated | Where-Object Tier -eq 'T0')
    $t0Accounts += @($results.AccountsExisted | Where-Object Tier -eq 'T0')

    if ($t0Accounts.Count -eq 0) {
        Write-Host "    No Tier 0 accounts to harden." -ForegroundColor DarkGray
    } else {
        Write-Host "    Hardening $($t0Accounts.Count) Tier 0 account(s)..." -ForegroundColor White

        foreach ($t0 in $t0Accounts) {
            $sam = $t0.SamAccountName

            # Add to Protected Users
            try {
                Add-ADGroupMember -Identity 'Protected Users' -Members $sam -ErrorAction Stop
                Write-Host "    [+] $sam → Protected Users" -ForegroundColor Green
                $results.HardeningApplied.Add([PSCustomObject]@{
                    SamAccountName = $sam
                    Setting        = 'Protected Users'
                    Status         = 'Applied'
                })
            } catch {
                if ($_.Exception.Message -match 'already a member') {
                    Write-Host "    [=] $sam — already in Protected Users" -ForegroundColor DarkGray
                    $results.HardeningApplied.Add([PSCustomObject]@{
                        SamAccountName = $sam
                        Setting        = 'Protected Users'
                        Status         = 'Already Applied'
                    })
                } else {
                    $errMsg = "Failed to add $sam to Protected Users: $($_.Exception.Message)"
                    Write-Host "    [!] $errMsg" -ForegroundColor Red
                    $results.Errors.Add($errMsg)
                    $results.HardeningApplied.Add([PSCustomObject]@{
                        SamAccountName = $sam
                        Setting        = 'Protected Users'
                        Status         = 'Failed'
                    })
                }
            }

            # Set AccountNotDelegated
            try {
                Set-ADUser -Identity $sam -AccountNotDelegated $true -ErrorAction Stop
                Write-Host "    [+] $sam → AccountNotDelegated = True" -ForegroundColor Green
                $results.HardeningApplied.Add([PSCustomObject]@{
                    SamAccountName = $sam
                    Setting        = 'AccountNotDelegated'
                    Status         = 'Applied'
                })
            } catch {
                $errMsg = "Failed to set AccountNotDelegated on ${sam}: $($_.Exception.Message)"
                Write-Host "    [!] $errMsg" -ForegroundColor Red
                $results.Errors.Add($errMsg)
                $results.HardeningApplied.Add([PSCustomObject]@{
                    SamAccountName = $sam
                    Setting        = 'AccountNotDelegated'
                    Status         = 'Failed'
                })
            }
        }
    }

    # ================================================================
    # Step 6 — Generate Report
    # ================================================================
    Write-Host "`n  ─── Step 5/5: Generating Report ────────────────────────" -ForegroundColor Yellow

    $htmlPath = Join-Path $OutputDir "MATI-Tiering-Phase2-$(Get-Date -Format 'yyyyMMdd-HHmmss').html"
    Export-TieringPhase2Html -Results $results -DomainDN $domainDN -TieringConfig $TieringConfig -OutputPath $htmlPath

    # Export JSON
    $jsonPath = Join-Path $OutputDir "MATI-Tiering-Phase2-$(Get-Date -Format 'yyyyMMdd-HHmmss').json"
    $results | ConvertTo-Json -Depth 10 | Set-Content -Path $jsonPath -Encoding UTF8
    Write-Host "    JSON : $jsonPath" -ForegroundColor DarkGray

    $sw.Stop()
    Write-Host ""
    Write-Host "  ══════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "   Phase 2 Complete — Duration: $([math]::Round($sw.Elapsed.TotalSeconds, 1))s" -ForegroundColor Cyan
    Write-Host "   Created  : $($results.AccountsCreated.Count) account(s)" -ForegroundColor White
    Write-Host "   Existed  : $($results.AccountsExisted.Count) account(s)" -ForegroundColor White
    Write-Host "   Skipped  : $($results.AccountsSkipped.Count) account(s)" -ForegroundColor White
    Write-Host "   Hardened : $(($results.HardeningApplied | Where-Object Status -eq 'Applied').Count) setting(s)" -ForegroundColor White
    if ($results.Errors.Count -gt 0) {
        Write-Host "   Errors   : $($results.Errors.Count)" -ForegroundColor Red
    }
    Write-Host "   Report   : $htmlPath" -ForegroundColor Cyan
    Write-Host "  ══════════════════════════════════════════════════════════`n" -ForegroundColor Cyan

    # Offer to open the report
    $openChoice = Read-Host "  Open HTML report in browser? (Y/N)"
    if ($openChoice -match '^[Yy]') {
        Start-Process $htmlPath
    }

    return $results
}
